### ISSUE TITLE
Custom layout options?

### ISSUE THREAD

**Issue by 3minus1** [strzibny/invoice_printer#21]
The logo's current position is bottom-left and is kind of counter-intuitive in my opinion. 

Would it be helpful to implement a feature that lets the user decide where to place certain components(like logo) on the invoice, change background opacity, etc?

**Comment by strzibny** [comment]
I was thinking before to what extend I am willing to support any customization. I do not want to support a complicated super flexible system. The only exception to the A4 vs letter format could be top left logo position. But because on working on making it print/letter friendly it's possible we come up with something flexible. If you have some ideas feel free to propose them.

**Comment by 3minus1** [comment]
Sounds fair. We could provide an option to either choose plain text Name OR a logo at the top-left position. What do you say? Or do you want to keep both Name AND logo?

**Comment by strzibny** [comment]
If there is (legal) need to write "invoice" or something else it can be actually appended into invoice number. So I am thinking that in case of a top left logo this text would be appended to the number field (prepend it). The sublabel though I think we would drop in this case. What do you think?

**Comment by 3minus1** [comment]
Sounds good to me! However, what if the seller/provider wants to place its company's name on the top instead of something like "invoice"?

**Comment by strzibny** [comment]
You mean if there is a case to put both logo and company name in the top left? Do you have this need?

**Comment by 3minus1** [comment]
I don't particularly have the need but what if some sellers/providers do?

**Comment by strzibny** [comment]
For me personally it is redundant since the name will be there in the provider box. So I am fine with it.
